articulate/terraform-provider-okta

- okta/config.go
- okta/provider.go
- okta/users.go
- okta/users_test.go
role is an optional field for a user. 
terraform config looks like:
```
resource "okta_users" "test" {
firstname = "test"
lastname  = "user"
email     = "witiz1932@teleworm.us"
role      = "ORG_ADMIN"
}
```
> add & update user role

- okta/config.go
- okta/provider_test.go
switching to default schema test instead
> authoritative server connect test fails on prod Okta accounts

- GNUmakefile
- okta/provider_test.go
- okta/resource_policy_rules.go
> Fix error thrown when a policy is deleted

- okta/resource_users.go
- okta/resource_users_test.go
updating some of the okta provider terraform things
> WIP - refactorin'

- Gopkg.lock
- okta/resource_identity_provider.go
- okta/resource_identity_provider_test.go
adding the ability to auto assign people who login through the okta social IDP to get auto assigned to groups - this will be needed to tie a group to the okta applications that we want a user to have access to (aka rise.com)
> Idp group assignment

- okta/provider.go
- okta/resource_group.go
- okta/resource_group_test.go
> Groupimus maximus

- Gopkg.lock
- Gopkg.toml
- README.md
- examples/README.md
- examples/okta_saml_app/README.md
- examples/okta_saml_app/custom_saml_app.tf
- examples/okta_saml_app/custom_saml_app_all_fields.tf
- examples/okta_saml_app/custom_saml_app_updated.tf
- examples/okta_saml_app/saml_app_with_groups_and_users.tf
- examples/okta_saml_app/saml_app_with_groups_and_users_updated.tf
- okta/app.go
- okta/config.go
- okta/fixtures.go
- okta/provider.go
- okta/provider_sweeper_test.go
- okta/resource_mfa_policy_test.go
- okta/resource_saml_app.go
- okta/resource_saml_app_test.go
- okta/resource_swa_app_test.go
- okta/resource_three_field_app.go
- okta/resource_three_field_app_test.go
I am going to start using test configuration as examples for consumers. This will help end users get started with our provider. Will convert all of them once I get someone to sign off on the idea. Also, no more skipped tests now that the rate limit management code is in use!!
> Add missing SAML properties, use SDK fork, and create fixture/example manager

- Gopkg.lock
- okta/resource_user.go
- okta/resource_user_test.go
Simply removing login field validation, depending on how you setup your user schema this may or may not be n email address. Fixes #100
> Updating SDK and removing validation for user login property

- Gopkg.lock
- Gopkg.toml
- examples/okta_user/okta_user_custom_attributes.tf
- examples/okta_user/okta_user_remove_custom_attributes.tf
- okta/app.go
- okta/resource_user_schema.go
I think due to this feature being off in some accounts, there is not default. If it is set it is considered an override.
> Remove master type default

- GNUmakefile
- examples/README.md
- examples/okta_bookmark_app/README.md
- examples/okta_bookmark_app/basic.tf
- examples/okta_bookmark_app/basic_updated.tf
- examples/okta_group/datasource.tf
- examples/okta_user/okta_user_group_assigned.tf
- examples/okta_user/okta_user_group_unassigned.tf
- okta/app.go
- okta/data_source_group_test.go
- okta/provider.go
- okta/resource_bookmark_app.go
- okta/resource_bookmark_app_test.go
- okta/resource_user_test.go
Add bookmark application that will be needed very soon. Very easy resource that happened to get overlooked.
> Add okta_bookmark_app

- examples/README.md
- examples/okta_inline_hook/README.md
- examples/okta_inline_hook/basic.tf
- examples/okta_inline_hook/basic_activated.tf
- examples/okta_inline_hook/basic_updated.tf
- go.mod
- go.sum
- okta/inline_hooks.go
- okta/provider.go
- okta/resource_inline_hooks.go
- okta/resource_inline_hooks_test.go
- okta/utils.go
Had a little free time so I terraformed hooks.
fixes #135
> Terraform Inline Hooks

- examples/okta_saml_app/custom_saml_app.tf
- examples/okta_saml_app/custom_saml_app_all_fields.tf
- examples/okta_saml_app/custom_saml_app_updated.tf
- go.sum
- okta/resource_saml_app.go
- okta/resource_saml_app_test.go
- okta/resource_user_schema.go
User schema must take an empty master value for accounts with
provisioning settings off.
fixes #145
> Fix user schema and add app entity id

- examples/okta_group_rule/basic_updated.tf
- okta/resource_group_rule.go
Hopefully to address https://github.com/articulate/terraform-provider-okta/issues/147
> resource_group_rule: in case expression is changed on ACTIVE rule, deactivate it prior to changing.

- examples/okta_group_rule/basic_group_update.tf
- okta/resource_group_rule.go
- okta/resource_group_rule_test.go
Corrected premature return and updated the test to test all scenarios.
fixes #147
> Fix Group Rule Update

- Makefile
Whitespace around setting variables
Added TEST_FILTER (-run filter)
Added fmtcheck to build-plugins target
TEST -> TEST_PKGS
TESTARGS -> TEST_ARGS
Move GOFMT_FILES from shell to make builtins
Squash duplicate -v if -v passed in TEST_ARGS for testacc target
print-% helper target
> Makefile refactor

- okta/authorization_server_policy_rules.go
- okta/resource_auth_server_policy_rule.go
set inline hooks on auth server
> Tie in inline hooks to auth server

- okta/user.go
If a user is not a super admin they will fail to read Admin roles. This
change will continue with the assumption that there aren't any admin
roles.
> allow non-admin users to interact with user/groups

- .travis.yml
- examples/okta_inline_hook/registration.tf
- okta/resource_inline_hooks.go
- okta/resource_inline_hooks_test.go
Add new inline hook and bump timeout for rate limit.
> Add registration inline hook

- okta/idp.go
- okta/idp_models.go
- okta/resource_idp_oidc.go
- okta/resource_idp_saml.go
- okta/resource_idp_social.go
* Add missing group sync properties
* Allow acs_url type ORG
> Add Properties for Syncing groups via IdP

- okta/config.go
Set provider user agent so it is more discernible.
> Set User Agent

- examples/README.md
- examples/okta_app_metadata_saml/datasource.tf
- examples/okta_app_saml/README.md
- examples/okta_app_saml/datasource.tf
- examples/okta_idp_saml/README.md
- okta/app.go
- okta/app_filter.go
- okta/data_source_app.go
- okta/data_source_app_saml.go
- okta/data_source_app_saml_metadata.go
- okta/data_source_app_saml_metadata_test.go
- okta/data_source_app_saml_test.go
- okta/provider.go
- okta/resource_app_saml.go
- okta/resource_app_saml_test.go
* add datasources for SAML app and SAML app metadata
* update docs
> SAML App Datasources

- examples/okta_app_oauth/oauth_app.tf
- examples/okta_idp_saml/datasource.tf
- examples/okta_user/custom_attributes.tf
- okta/resource_app_oauth.go
- okta/resource_app_oauth_test.go
> Allow setting of client secret

- examples/okta_app_metadata_saml/datasource.tf
- examples/okta_user/datasource.tf
- examples/okta_user/datasource_create_user.tf
- okta/data_source_user_test.go
- okta/resource_user_schema.go
- okta/resource_user_test.go
- okta/user.go
* Write test to fail to confirm bug report
* Fix schema for user data sources
* Remove debug line
Fixes #206
> Fix data source for user with custom attributes

- okta/resource_idp_oidc.go
- okta/resource_idp_oidc_test.go
- okta/resource_idp_saml_test.go
- okta/resource_idp_social.go
- okta/resource_idp_social_test.go
* Fix OIDC IdP issuer mode setting, and add it to social IdP.
For simplicities sake I decided to avoid defining a variable for issuer mode. I probably should be using a code generator or a variable there but meh this is easy to understand at a glance.
fixes #214
> Add issuer_mode setting to social idp

- examples/README.md
- examples/okta_group_roles/README.md
- examples/okta_group_roles/all_roles.tf
- examples/okta_group_roles/basic.tf
- okta/group_role.go
- okta/idps.go
- okta/provider.go
- okta/resource_group_roles.go
- okta/resource_group_roles_test.go
- okta/user.go
Implement admin group roles resource.
Fixes #183
> Admin Groups

- examples/README.md
- examples/okta_template_email/README.md
- examples/okta_template_email/basic.tf
- okta/provider.go
- okta/resource_template_email.go
- okta/resource_template_email_test.go
- okta/templates.go
Add the ability to create and manage custom email templates.
> Email templates

- CHANGELOG.md
- okta/user.go
Also renamed some vars for readability.
Fixes #225
> Add the ability to unlock users that are locked out

- examples/okta_group_roles/all_roles.tf
- examples/okta_group_roles/basic.tf
- examples/okta_user_base_schema/basic.tf
- examples/okta_user_base_schema/updated.tf
- go.mod
- go.sum
- okta/app.go
- okta/config.go
- okta/provider_sweeper_test.go
- okta/resource_user.go
- okta/resource_user_schema.go
- okta/user.go
- okta/utils.go
Fixes #238 
* Update SDK to get assignmentType (required me sync the fork with upstream, went to v1.0.0 due to API changes)
* Filter out group roles
> Ignore group roles

- okta/resource_user_base_schema.go
- okta/resource_user_schema.go
- okta/resource_user_schemas.go
Speeling meestake in word 'integer'. Fixes #243 ?
> typo: interger -> integer

- .github/main.workflow
- examples/okta_policy_rule_idp_discovery/app_exclude_platform.tf
- examples/okta_policy_rule_idp_discovery/app_include.tf
- okta/resource_policy_rule_idp_discovery.go
- okta/resource_policy_rule_idp_discovery_test.go
- okta/resource_policy_rule_password_test.go
Test the `app_include`. It is known broken atm. Fix on its way with #253
> Add idp discovery policy rule test

- examples/okta_idp_social/auto_provision_disabled.tf
- okta/idp.go
- okta/resource_idp_social_test.go
> Allow disabling of auto provisioning on IdPs

- examples/okta_auth_server_claim/basic_group.tf
- okta/resource_auth_server_claim.go
- okta/resource_auth_server_claim_test.go
> Correct START_WITH -> STARTS_WITH for auth server claim

- okta/resource_okta_auth_server_scope.go
- sdk/authorization_server_scopes.go
The scopes support a default flag.
> Scopes can have a default

- examples/okta_user_schema/README.md
- examples/okta_user_schema/array_enum.tf
- examples/okta_user_schema/array_string.tf
- examples/okta_user_schema/array_string_updated.tf
- okta/resource_okta_app_user_base_schema.go
- okta/resource_okta_user_base_schema.go
- okta/resource_okta_user_schema_test.go
- okta/user_schema.go
- sdk/user_schema_models.go
Add support for `array_enum` and `array_one_of`.
fixes #281
> Support array enum for user and app user schema

- examples/okta_user_base_schema/username.tf
- okta/resource_okta_app_user_base_schema.go
- okta/resource_okta_user_base_schema.go
- okta/resource_okta_user_base_schema_test.go
- okta/user_schema.go
- sdk/user_schema_models.go
- website/docs/r/app_user_base_schema.html.markdown
- website/docs/r/user_base_schema.html.markdown
> Push up support for pattern property

- CHANGELOG.md
- LICENSE
- examples/okta_auth_server/dependency.tf
- okta/resource_okta_auth_server.go
- okta/resource_okta_auth_server_test.go
- sdk/mappings.go
- website/docs/d/default_policy.html.markdown
- website/docs/d/everyone_group.html.markdown
- website/docs/d/group.html.markdown
- website/okta.erb
An initial DRAFT for the profile mappings API usage 
https://developer.okta.com/docs/reference/api/mappings/#getting-started
> Skeleton/DRAFT for Profile mappings

- examples/okta_app_group_assignment/force_new_update.tf
- examples/okta_app_group_assignment/updated.tf
- examples/okta_auth_server/dependency.tf
- examples/okta_auth_server/full_stack_with_client.tf
- okta/app_test.go
- okta/resource_okta_app_group_assignment.go
- okta/resource_okta_app_group_assignment_test.go
- okta/resource_okta_app_user.go
- okta/resource_okta_app_user_test.go
- okta/resource_okta_user.go
* Better `okta_app_group_assignment`
* Ensure we don't error in Exists when there is a 404. 
This fixes #313, and fixes #307
> Fix user 404 bug and fix app_user/group import logic

- examples/okta_profile_mapping/basic.tf
- examples/okta_profile_mapping/prevent_delete.tf
- examples/okta_profile_mapping/updated.tf
- okta/provider.go
- okta/resource_okta_profile_mapping.go
- okta/resource_okta_profile_mapping_test.go
- sdk/mappings.go
- website/docs/r/profile_mapping.html.markdown
- website/okta.erb
Adding new resource `okta_profile_mapping` that manages Okta Mapping resources by source id.
Fixes #246
> okta_profile_mapping resource

- okta/utils.go
Fixes #338
Also maintains the order in which elements are written to the rerturned map.
> Changes buildSchema to not modify its arguments

- okta/app.go
Causing an error to get swallowed on #307
> Safely check for 404 when retrieving app

- CHANGELOG.md
- okta/resource_okta_user_base_schema.go
- okta/resource_okta_user_schema.go
- okta/user_schema.go
> Ensure we sync schema index so it shows up in plan on import

- website/docs/r/auth_server_policy_rule.html.markdown
> Remove spurious quote in okta_auth_server_policy_rule docs.

- .hashibot.hcl
Taking a shot in the dark with the hashibot to migrate issues. There are no docs on the matter, copying an existing example.
> Hashibot issue migrator
