.gitignore
Gopkg.lock
okta/resource_identity_provider.go

Was getting a `panic: runtime error: invalid memory address or nil pointer dereference` error on the `okta_identity_provider` resource due to a `You do not have permission to access the feature you are requesting` error we were receiving from okta.  Needed to move the `d.SetId(returnedIdp.ID)` after the error check and then surface the error to terraform during the apply to make it more clear what was going on there.

Better error logging

---

GNUmakefile
okta/resource_identity_provider.go

give the `okta_identity_provider` resource the ability to get imported from existing resources in okta back to state.
testing this import locally revealed that I should be using the length of the returned `idp.Policy.Provisioning.Groups.Assignments` slice of strings to determine if `policy_provisioning_group_assignments` should be getting set in state.  using `terraform import` showed this was missing in state even though it existed on the resource because import is just using the read function.

add idp importer function

---

okta/resource_identity_provider.go

my custom `resourceOktaIdentityProviderImport` does the same thing that the built in `schema.ImportStatePassthrough` helper function does so let's just use that for the `Importer` going forward in idp.tf

update the importer function in idp.tf

---

okta/resource_trusted_origin.go

the `scopes` parameter in the `okta_trusted_origin` resource isn't Optional; updating it to be Required in the Terraform schema

change scopes to Required in okta_trusted_origin resource

---

GNUmakefile

adding a `make ship` command to the GNUmakefile to automate the shipping to our providers bucket and also help us remember to bump the version number before it copies the provider to S3.

add a make ship command to the GNUmakefile

---

Gopkg.lock
Gopkg.toml
okta/policy.go
okta/policy_rule.go
okta/resource_password_policy.go
okta/resource_password_policy_rule.go
okta/resource_password_policy_test.go
okta/resource_sign_on_policy.go
okta/resource_sign_on_policy_rule.go

This allowed me to greatly reduce the fluff in the CRUD functions. Also stopped the practice of import within the create function. Now when you attempt to create a resource with an existing name, the API errors and you are forced to use the import command. Yay!

Fix password policy bug and add Exist and Import functionality

---

okta/resource_user.go
okta/resource_user_test.go
okta/user.go
okta/utils.go

utilizing a `custom_profile_attributes` map that will allow folks to control the setting of custom attributes to their users that is outside of the standard attributes provided by Okta (like firstName, lastName, company, etc.)  This does require that the attribute be set beforehand to the user profile schema as per their [user API documentation](https://developer.okta.com/docs/api/resources/users#profile-object).

allow custom profile attributes to be set on an okta user

---

okta/resource_user.go
okta/resource_user_test.go
okta/user.go

adding the ability to assign/remove [group memberships to an Okta user](https://developer.okta.com/docs/api/resources/groups#add-user-to-group) via the `okta_user` resource using the `group_memberships` list attribute.

add group_memberships field to the okta_user resource

---

GNUmakefile
examples/okta_saml_app/import.tf
okta/resource_saml_app.go
okta/resource_saml_app_test.go
okta/resource_three_field_app_test.go

preconfigured_app was not be read into state, fix this and add import test. A change in the preconfigured app requires recreation otherwise Okta just ignores it, and suppress diff for computed name when preconfigured_app is not set in config.

Fix SAML App import bug

---

GNUmakefile
okta/app.go
okta/utils.go

An app we use was manually manipulated, and due to this, when a group was removed in the config, the 404 caused the provider to error out. In retrospect this is where having an actual resource for each of these associations would be nice because of the Exists function, though the config would explode in size so leaving it as is!

Ignore 404 when removing group and user associations

---

okta/resource_user.go
okta/resource_user_test.go

Fixes #104 
Allow user to be deprovisioned without an error and only make a profile update request if there is a change.

Allow user to be deprovisioned

---

okta/app.go
okta/data_source_app.go
okta/utils.go

I found out that Header.Get does not return the raw header, it previously parses the headers into a slice of strings, .Get gives you the first one but I realized there was a utility function for this anyways!
Added the ability to search active apps only to speed things up, as well as increase the limit param to avoid hitting rate limits constantly.

RequestExecutor does not take query params, manually build the URL

---

README.md
examples/okta_saml_app/saml_app_with_groups_and_users.tf

Going to link this in a `how-do-i`. I haven't been great at being real clear about Okta's API limitations as I run into them.

Clearly enumerate resources not exposed by Okta

---

okta/resource_user_schema.go

Allow specifying :  "type" : "object" as supported by Okta.

Add "object" attribute type to user schema resource

---

Gopkg.lock
okta/resource_saml_app.go

This includes initialising proxy settings, etc.
cleanhttp is already pulled in as a dependency so I figured it's reasonable to use it instead. This is the only occurrence of directly creating an `http.Client` instance that I could see in the code so I think it's the only piece left to fix #130

Switch to using cleanhttp

---

okta/resource_saml_app.go

This works without conversion for the XML parsing but Terraform will
ignore it as an attribute value so cast it to a string.
Fixes #131

Metadata is returned as bytes now

---

examples/README.md
examples/okta_policy_mfa/README.md
examples/okta_policy_mfa/basic.tf
examples/okta_policy_mfa/basic_updated.tf
examples/okta_policy_password/README.md
examples/okta_policy_password/basic.tf
examples/okta_policy_password/basic_updated.tf
examples/okta_policy_rule_signon/README.md
examples/okta_policy_rule_signon/basic.tf
examples/okta_policy_rule_signon/basic_updated.tf
examples/okta_policy_signon/README.md
examples/okta_policy_signon/basic.tf
examples/okta_policy_signon/basic_inactive.tf
examples/okta_policy_signon/basic_renamed.tf
okta/policy.go
okta/policy_rule.go
okta/resource_policy_mfa_test.go
okta/resource_policy_password_test.go
okta/resource_policy_rule_sign_on_test.go
okta/resource_policy_sign_on_test.go

Despite what Okta's docs purport you cannot exclude groups from policies and you cannot include users from policy rules. Updating the provider to reflect that.

Fix Okta Policy user/group include/exclude

---

okta/config.go

This makes debugging for developers & users of this provider easier by exposing all requests & responses in the log (when >DEBUG severity is set https://www.terraform.io/docs/internals/debugging.html).
This is to assist in debugging https://github.com/articulate/terraform-provider-okta/issues/162

Enable request/response logging for debugging

---

README.md

The Makefile doesn't seem to have a 'bin' rule?

s/make bin/make build/

---

okta/resource_app_oauth.go

OAuth application types allow particular grant types. We were missing a valid
option for `web` and `browser` application types. It appears Okta's docs are missing the one for `web` as well. Reported the discrepancy to them.
fixes #169

Correct OAuth app validation logic

---

okta/app.go

Noticed we are not respecting `after` links on these calls. Need to fix this. For now just setting a high limit.

Missing Pagination Support

---

okta/resource_auth_server.go

Auth server issuer should be computed

---

.travis.yml
okta/resource_user.go

Recent improvement had a typo in it. Tests were passing because the state was technically set. Not sure if it is worth making downstream calls specifically to get the test to fail.

Property Typo

---

go.mod
go.sum
okta/api_supplement.go

Due to a bug in Okta's SDK we had to handle our own request. In order to
use the same retry/backoff method we wrote in our forked version, we
just had to expose it publicly.

Metadata endpoint handler must use same retry/backoff approach

---

examples/okta_user/import.tf
okta/resource_app_saml_test.go
okta/resource_user.go
okta/resource_user_test.go

Pass whatever is passed to the import command to Okta. Let it error or return a user with an id. This will allow us to import users via email.
Fixes #194 (improvement determined through the discussion there)

Support importing user by email or id

---

examples/okta_app_oauth/oauth_app.tf
okta/resource_app_oauth.go
okta/resource_app_oauth_test.go

Allow oauth app client_id to be set using `custom_client_id`
Fixes #208

Allow consumers to set client_id on oauth applications

---

CHANGELOG.md
examples/okta_user/all_attributes.tf
okta/resource_user_schema.go
okta/resource_user_test.go

If subschema does not come back in schema payload, backoff, and retry. Occasionally a read immediately after a created results in a missing subschema.
Fixes #144 
Need to keep an eye on this one, this issue appears to be very intermittent. I do believe this will correct it though, as hacky as it is.

Fix ocassional user schema panic

---

okta/idp.go
okta/idp_models.go
okta/resource_idp_social.go

I was not able to create a resource_idp_social because I needed to match the social provider key with a custom field in OKTA schema that I created. In order to do that match_type attribute should be set to CUSTOM. In that case match_attribute becomes required and it should contain the name of the custom field. 
Today there is no support for that match_attribute in the plugin. This PR addresses this issue. It modifies the schema and resource itself to support the additional attribute.

Add support for Match Attribute in idp social resource

---

examples/okta_idp_social/basic.tf
okta/resource_idp_social.go
okta/resource_idp_social_test.go

This PR is related to https://github.com/articulate/terraform-provider-okta/pull/229 PR that did not have acceptance test included. 
These changes will have a test case that will create a custom field in Okta schema and will use that custom field to in matching_attribute
One question I have - I had to modify the schema for in resource_idp_social.go so the validation won't fail during the acceptance testing. However, it was not required during the actual change.

Add acceptance testing case for matching_attribute in idp social

---

.gitignore
examples/okta_user_base_schema/README.md
examples/okta_user_base_schema/basic.tf
examples/okta_user_base_schema/updated.tf
okta/provider.go
okta/provider_sweeper_test.go
okta/resource_user_basic_schema.go
okta/resource_user_basic_schema_test.go

We are needed possibility to change permissions in the user schema via terraform-provider-okta.
This update provide this possibilities.

Add support modify permission in the user basic schema fields

---

examples/okta_policy_rule_signon/excluded_network.tf
examples/okta_user_base_schema/basic.tf
examples/okta_user_base_schema/updated.tf
okta/policy_rule.go
okta/resource_policy_rule_sign_on_test.go

Okta's API only accepts and Include or Exclude. Instead of using the `if` mumbo jumbo just using my conversion or nullable logic and the `omitempty` tag will remove it when it is marshalled to JSON.
Fixes #236

Create Sign On Rule With Network Include or Exclude

---

okta/idp_discovery_rule.go
okta/resource_policy_rule_idp_discovery.go

Thanks for making an Okta terraform provider available for all!
We found a few issues with the idp_discovery_profile resource.  It appears it doesn't work if you didn't provide UserIdentifier or the Platform.  Additionally (and most importantly to our use case) the app config doesn't seem to match the [api for Application and App Instance Condition](https://developer.okta.com/docs/reference/api/policy/#application-and-app-instance-condition-object).
Without them provided, it was creating empty objects in the request `"userIdentifier": {}` or `"platform": {}` would cause the Okta api to throw an exception.
It looks like okta may have a deserialization issue and throws 500.  You can get around the platform one by adding the following to the `okta_policy_rule_idp_discovery`
```HCL …
```

Fixing mismatching idp_discovery_profile api

---

okta/idp.go

Okta supports SHA-256 and SHA-1 for saml idp integrations.

Add SHA-1 as a valid algorithm

---

okta/resource_idp_saml.go

Fixes Bug where updates to saml idp causes new audience and therefore breaks the federation:
The Okta idp put call should persist the audience in the [credentials section](https://developer.okta.com/docs/reference/api/idps/#saml-2-0-trust-credentials-object) so that the audience doesn't change when it is making a PUT request to the okta idps endpoint.
The Put doesn't include the audience in the "credentials" section and therefore okta is generating a new audience for the saml idp integration.
The put request generated by the update operation:
```
[DEBUG] Okta API Request Details: 
---[ REQUEST ]--------------------------------------- 
PUT /api/v1/idps/********************* HTTP/1.1 
Host: ********************* .okta.com 
User-Agent: okta-sdk-golang/0.1.0 golang/go1.12.7 darwin/amd64 …
```

Supply the audience so that updates do not change the audience

---

okta/resource_policy_rule_idp_discovery.go

When creating an idp discovery rule, if you don't specify a body for the user identity role, terraform is generating an empty user identity block that is causing okta to throw a 500 as it is failing to deserialize the block.
This change makes the block only populated if the user identifier type is provided as it is a [required parameter](https://developer.okta.com/docs/reference/api/policy/#user-identifier-condition-object).  I couldn't figure out how to get it to omit the parameter if all children objects are empty.
There is probably a nicer way to do this in GO, but as I am new this was the quickest way I found to suppress this field with an inner if statement as I could figure out how to append it to the if above.

Don't populate the user identifier if type is blank

---

okta/resource_policy_rule_idp_discovery.go

Found that in the commit where I fixed the app conditions of the idp discovery policy, I copied an example from the flatten platform which had a typo in it.
I have fixed that typo then noticed that it was still detecting a diff for apps even when there was no diff, after debugging I found that the flattened array was still empty.  Not sure why from a GO perspective but I noticed in other methods the append operation used (and appeared to work) so I adopted that.

Fix state diff idp discovery

---

okta/idp.go
okta/resource_idp_oidc.go
sdk/idp_models.go

The user info url and binding are optional for oidc idp configuration (as per the okta ui), the terraform was requiring it.
The api documentation has all those endpoints readonly so I cant trust those for this one.

Make the user info url and binding optional

---

.travis.yml
README.md

fixes #267 
From release notes: `As of Go 1.13, the go command by default downloads and authenticates modules using the Go module mirror and Go checksum database run by Google. `

Update to Go 1.13

---

okta/user_schema.go
sdk/user_schema_models.go

The external name of the user profile was not exposed.
This pr exposes this field.  I don't quite understand the base vs subschema so this may also need to be added in the base, but this fix meets our needs.

expose external_name to user profile

---

okta/resource_okta_app_oauth.go

As part of PR #265, custom_profile_attributes was supposed to be renamed to profile. I mistakenly didn't change this in all of the places I needed to.
This was not picked up by the acceptance tests. While they check that the application schema is correct, they don't check that the application built in Okta reflects this schema.
Is this how all of the tests work? Is there something specifically wrong with my tests?
Apologies for the questions, this is my first experience with both Go and Terraform.

custom_profile_attributes was renamed to profile

---

examples/okta_app_oauth/custom_attributes.tf
examples/okta_app_oauth/group_for_groups_claim.tf
examples/okta_app_user/basic_profile.tf
okta/resource_okta_app_group_assignment.go
okta/resource_okta_app_group_assignment_test.go
okta/resource_okta_app_user.go
okta/resource_okta_app_user_test.go

Allow profile to be set. Note: I had a lot of trouble finding a working group example. All attempts resulted in Okta API errors. It is possible this configuration only works once API Integration is setup.
fixes #234 
fixes #244

Allow app_users and app_group_assignments to have optional profile

---

examples/okta_auth_server/README.md
examples/okta_auth_server/full_stack_with_client.tf
okta/resource_okta_auth_server_policy_rule.go
okta/resource_okta_auth_server_test.go

* There is a new 5y upper limit on the refresh token window, updating validation logic to match.
* Add a `client_whitelist` example that refers to an app
This closes #283, closes #284

Extend refresh token window

---

CHANGELOG.md
examples/okta_auth_server/dependency.tf
okta/resource_okta_auth_server.go
okta/resource_okta_auth_server_test.go

* Fix auth server issue that results in a panic. Turns out in certain circumstances Okta is not returning the expected credential parameters. When this happens, it results in a panic due to the way the struct is setup in the SDK. Fix that.
* Turns out Okta does not accept rotation mode changes on create, it simply ignores them. Make sure we run update for non-default scenarios.
Fixes #299, #287

Auth server issues

---

okta/resource_okta_app_group_assignment.go

This error #307 still happens when updating AppGroupAssignments: 
```2019-10-29T18:19:35.438+0100 [DEBUG] plugin.terraform-provider-okta_v3.0.30_x4: -----------------------------------------------------
2019-10-29T18:19:35.440+0100 [DEBUG] plugin.terraform-provider-okta_v3.0.30_x4: panic: interface conversion: interface {} is nil, not string
2019-10-29T18:19:35.440+0100 [DEBUG] plugin.terraform-provider-okta_v3.0.30_x4: 
2019-10-29T18:19:35.440+0100 [DEBUG] plugin.terraform-provider-okta_v3.0.30_x4: goroutine 20 [running]:
2019-10-29T18:19:35.440+0100 [DEBUG] plugin.terraform-provider-okta_v3.0.30_x4: github.com/articulate/terraform-provider-okta/okta.resourceAppUserRead(0xc000143960, 0x1bd55e0, 0xc0001480e0, 0xc0002501e0, 0x14)
2019-10-29T18:19:35.440+0100 [DEBUG] …
```

Fix wrong return of resourceAppGroupAssignmentUpdate

---

website/docs/r/app_group_assignment.html.markdown

Missing argument in `app_group_assignment` resource docs.

Document `app_group_assignment.profile` argument

---

website/docs/r/app_group_assignment.html.markdown
website/docs/r/app_user.html.markdown

When managing application group assignments via `app_group_assignment` resource
the application resource's group management must be disabled using `lifecycle.ignore_changes`
attribute to avoid removal of externally added assignments. Same applies
to `app_user` resource.
While this behaviour is shown in examples, it is best to warn users by
adding this to docs too.
See #322

Document the need for lifecycle argument

---

website/docs/r/template_email.html.markdown

The documentation incorrectly shows that the okta id is used to import email templates. The current implementation uses the email template type.
I tested with ids and it failed, then with types and they succeeded.

Switch id with type in import documentation

---

examples/okta_app_oauth/basic.tf
examples/okta_app_oauth/custom_attributes.tf
examples/okta_app_oauth/remove_custom_attributes.tf
okta/resource_okta_app_oauth.go
okta/resource_okta_app_oauth_test.go
website/docs/r/app_oauth.html.markdown

Enables specification of `client_id` for oauth app resource. Fixes: https://github.com/articulate/terraform-provider-okta/issues/372
Following the deprecation guide in: https://www.terraform.io/docs/extend/best-practices/deprecations.html
_`custom_client_id` changes does not recreate resource_: This is a change in existing provider behavior. However, its an easy way to ensure that users can migrate from `custom_client_id` to `client_id` _without recreating their apps_. To migrate, users would simply change the variables from `custom_client_id` to `client_id`, apply and done. 
The other way would be to edit in statefile, or to remove from state and import, both of which involve more effort. I believe this is a reasonable trade-off considering that the next release will remove the …

Enable setting client_id for resource_okta_app_oauth

---

examples/okta_user/datasource.tf
okta/data_source_okta_user.go
okta/data_source_okta_user_test.go
okta/data_source_okta_users.go
okta/user.go
website/docs/d/user.html.markdown

Fixes #336 
I've added an additional optional attribute to the user data source called `user_id`. We can now search for a single user like so:
```
data "okta_user" "example" {
user_id = "00u22mtxlrJ8YkzXQ357"
}
```
Examples & documentation are updated, and I've run acceptance tests for the user & users data sources. Let me know if I've missed anything and feel free to nitpick! This is my first time with Go, Terraform and Okta.

Allow user to be retrieved by id

---

examples/okta_app_oauth/service_with_jwks.tf
okta/resource_okta_app_oauth.go
okta/resource_okta_app_oauth_test.go
sdk/app_oidc_models.go

This isn't particularly well documented by Okta. You'll see it listed
under https://developer.okta.com/docs/reference/api/apps/#credentials -
and an example including the JWKS elements is available here:
https://developer.okta.com/docs/reference/api/apps/#request-example-10
The general idea behind this is described at
https://developer.okta.com/docs/reference/api/oidc/#jwt-with-private-key
\- basically, a private key is held client side. The associated public
key is provided to Okta. Client authentication is achieved by signing a
JWT containing the appropriate client ID. Okta then check the JWT was
signed using one of the keys associated with that client.
As seems to be the case with quite a few things, this isn't covered by
their SDK. I've tried to work around this by defining structs …

Add support for token_endpoint_auth_method = private_key_jwt

---

README.md

Hashicorp has once again released this provider officially. It sounds like Okta is fully on board this time around. I updated the README to point users over there. I think it would also be helpful to have it in the repository description. I will also work on getting the issues moved over. Due to my lack of access, I may need assistance with that.

Official Provider Part Deux
